version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: 'php artisan migrate && php artisan serve'
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: debian
      POSTGRES_DB: smarthome
    ports:
        - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080