version: "2"
services:
  app:
    image: smarthome-app
    build: .
    container_name: "smarthome-app"
    volumes:
      - .:/app
      - /app/vendor
    env_file: .env.example
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: "smarthome-db"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: debian
      POSTGRES_DB: smarthome
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: "smarthome-adminer"
    restart: always
    ports:
      - 8080:8080
